packages:
  - frontend
  - backend
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.14.1
  '@types/node': ^24.0.1
  '@unocss/eslint-plugin': ^66.2.1
  '@unocss/preset-rem-to-px': ^66.2.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.29.0
  fastify: ^5.3.3
  tsdown: ^0.12.7
  tsx: ^4.20.3
  typescript: ^5.8.3
  unocss: ^66.2.1
  unocss-preset-scrollbar: ^3.2.0
  vite: ^6.3.5
  vue: ^3.5.13
  vue-tsc: ^2.2.10

onlyBuiltDependencies:
  - esbuild
